package vista;

import controlador.Analizador;
import controlador.Cargador;
import controlador.CursorListener;
import controlador.GeneradorReporte;
import controlador.Limpiador;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.KeyStroke;
import javax.swing.text.MutableAttributeSet;

/**
 *
 * @author usuario
 */
public class Gui extends javax.swing.JFrame {

    private final Analizador analizador;
    private final GeneradorReporte generadorReporte;
    private final ReporteGUI reporteGUI;
    private final Limpiador limpiador;

    /**
     * Creates new form Gui
     */
    public Gui() {
	initComponents();
	limpiador = new Limpiador(this);
	reporteGUI = new ReporteGUI(this, false);
	generadorReporte = new GeneradorReporte(this);

	analizador = new Analizador(textPaneEditor, textPaneOutput, generadorReporte, limpiador);
	textPaneEditor.addCaretListener(new CursorListener(textPaneEditor, labelFila, labelColumna));
	//textPaneEditor.addKeyListener(new TabuladorListener(textPaneEditor, 8));
	usarEspacio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JToolBar jToolBar1 = new javax.swing.JToolBar();
        javax.swing.JToolBar.Separator jSeparator3 = new javax.swing.JToolBar.Separator();
        botonArchivo = new javax.swing.JButton();
        javax.swing.JToolBar.Separator jSeparator1 = new javax.swing.JToolBar.Separator();
        botonAyuda = new javax.swing.JButton();
        javax.swing.JToolBar.Separator jSeparator2 = new javax.swing.JToolBar.Separator();
        botonAcerdaDe = new javax.swing.JButton();
        javax.swing.JToolBar jToolBar2 = new javax.swing.JToolBar();
        javax.swing.Box.Filler filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        botonAnalizar = new javax.swing.JButton();
        javax.swing.JToolBar.Separator jSeparator4 = new javax.swing.JToolBar.Separator();
        botonLimpiar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        botonGenerarReporte = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        textPaneEditor = new javax.swing.JTextPane();
        panelLineaEditor = new javax.swing.JPanel();
        panelLineaError = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        textPaneOutput = new javax.swing.JTextPane();
        javax.swing.JLabel labelOutput = new javax.swing.JLabel();
        javax.swing.JToolBar jToolBar3 = new javax.swing.JToolBar();
        javax.swing.Box.Filler filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelFila = new javax.swing.JLabel();
        javax.swing.JToolBar.Separator jSeparator5 = new javax.swing.JToolBar.Separator();
        javax.swing.JToolBar.Separator jSeparator6 = new javax.swing.JToolBar.Separator();
        labelColumna = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator3);

        botonArchivo.setText("Archivo");
        botonArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonArchivo.setFocusable(false);
        botonArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonArchivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArchivoActionPerformed(evt);
            }
        });
        jToolBar1.add(botonArchivo);
        jToolBar1.add(jSeparator1);

        botonAyuda.setText("Ayuda");
        botonAyuda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAyuda.setFocusable(false);
        botonAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAyuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAyudaActionPerformed(evt);
            }
        });
        jToolBar1.add(botonAyuda);
        jToolBar1.add(jSeparator2);

        botonAcerdaDe.setText("Acerca de");
        botonAcerdaDe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAcerdaDe.setFocusable(false);
        botonAcerdaDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAcerdaDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAcerdaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcerdaDeActionPerformed(evt);
            }
        });
        jToolBar1.add(botonAcerdaDe);

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setRollover(true);
        jToolBar2.add(filler1);

        botonAnalizar.setText("Analizar");
        botonAnalizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAnalizar.setFocusable(false);
        botonAnalizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAnalizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarActionPerformed(evt);
            }
        });
        jToolBar2.add(botonAnalizar);
        jToolBar2.add(jSeparator4);

        botonLimpiar.setText("Limpiar Pantalla");
        botonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLimpiar.setFocusable(false);
        botonLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });
        jToolBar2.add(botonLimpiar);
        jToolBar2.add(jSeparator7);

        botonGenerarReporte.setText("Abrir Ventana de Reportes");
        botonGenerarReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonGenerarReporte.setFocusable(false);
        botonGenerarReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGenerarReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarReporteActionPerformed(evt);
            }
        });
        jToolBar2.add(botonGenerarReporte);

        jScrollPane1.setViewportView(textPaneEditor);

        panelLineaEditor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelLineaEditorLayout = new javax.swing.GroupLayout(panelLineaEditor);
        panelLineaEditor.setLayout(panelLineaEditorLayout);
        panelLineaEditorLayout.setHorizontalGroup(
            panelLineaEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLineaEditorLayout.setVerticalGroup(
            panelLineaEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelLineaError.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelLineaErrorLayout = new javax.swing.GroupLayout(panelLineaError);
        panelLineaError.setLayout(panelLineaErrorLayout);
        panelLineaErrorLayout.setHorizontalGroup(
            panelLineaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        panelLineaErrorLayout.setVerticalGroup(
            panelLineaErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textPaneOutput.setEditable(false);
        textPaneOutput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(textPaneOutput);

        labelOutput.setText("OUTPUT:");

        jToolBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar3.setRollover(true);
        jToolBar3.add(filler2);

        labelFila.setText("fila");
        jToolBar3.add(labelFila);
        jToolBar3.add(jSeparator5);
        jToolBar3.add(jSeparator6);

        labelColumna.setText("columna");
        jToolBar3.add(labelColumna);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLineaError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLineaEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelOutput, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                        .addComponent(jToolBar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLineaEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLineaError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarActionPerformed
	// TODO add your handling code here:
	if (!textPaneEditor.getText().isBlank()) {
	    analizador.realizar();
	} else {
	    JOptionPane.showMessageDialog(this, "el editor esta vacio, abra un archivo o escriba en el editor");
	}
    }//GEN-LAST:event_botonAnalizarActionPerformed


    private void botonGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarReporteActionPerformed
	// TODO add your handling code here:
	if (!reporteGUI.isVisible()) {
	    reporteGUI.setVisible(true);
	} else {
	    reporteGUI.setVisible(false);
	}
    }//GEN-LAST:event_botonGenerarReporteActionPerformed

    private void botonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArchivoActionPerformed
	// TODO add your handling code here:
	Cargador cargadorArchivo = new Cargador(this);
	cargadorArchivo.cargarArchivoEn(new SelectorDeArchivo());
    }//GEN-LAST:event_botonArchivoActionPerformed

    private void botonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAyudaActionPerformed
	// TODO add your handling code here:
	mostrarAyuda();
    }//GEN-LAST:event_botonAyudaActionPerformed

    private void botonAcerdaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcerdaDeActionPerformed
	// TODO add your handling code here:
	JOptionPane.showMessageDialog(this, "Practica 1 Lab. Lenguajes Formales y de Programacion\n Analizador Lexico.\n Elaborado por Carlos Vasquez");
    }//GEN-LAST:event_botonAcerdaDeActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
	// TODO add your handling code here:
	limpiador.limpiarTodo();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	
	 */
//	try {
//	    UIManager.setLookAndFeel(new NimbusLookAndFeel());
//	} catch (Exception ex) {
//	    System.err.println("Failed to initialize LaF");
//	}

//	try {
//	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//		if ("Nimbus".equals(info.getName())) {
//		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//		    break;
//		}
//	    }
//	} catch (ClassNotFoundException ex) {
//	    java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	} catch (InstantiationException ex) {
//	    java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	} catch (IllegalAccessException ex) {
//	    java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//	    java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Gui().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcerdaDe;
    private javax.swing.JButton botonAnalizar;
    private javax.swing.JButton botonArchivo;
    private javax.swing.JButton botonAyuda;
    private javax.swing.JButton botonGenerarReporte;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JLabel labelColumna;
    private javax.swing.JLabel labelFila;
    private javax.swing.JPanel panelLineaEditor;
    private javax.swing.JPanel panelLineaError;
    private javax.swing.JTextPane textPaneEditor;
    private javax.swing.JTextPane textPaneOutput;
    // End of variables declaration//GEN-END:variables

    public ReporteGUI getReporteGUI() {
	return reporteGUI;
    }

    public Analizador getAnalizador() {
	return analizador;
    }

    public JTextPane getTextPaneEditor() {
	return textPaneEditor;
    }

    public JTextPane getTextPaneOutput() {
	return textPaneOutput;
    }

    public Limpiador getLimpiador() {
	return limpiador;
    }

    private void usarEspacio() {
	Action spaceAction = new AbstractAction() {
	    @Override
	    public void actionPerformed(ActionEvent e) {
		MutableAttributeSet mas = textPaneEditor.getInputAttributes();
		mas.removeAttributes(mas);
	    }
	};

	KeyStroke spaceKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0);
	textPaneEditor.getInputMap().put(spaceKeyStroke, "doSpaceAction");
	textPaneEditor.getActionMap().put("doSpaceAction", spaceAction);
    }

    private void mostrarAyuda() {
	String mensaje = "Manual de usuario en el siguiente enlace: ";
	String linkTexto = "Visitar el sitio web";
	String url = "https://docs.google.com/document/d/11UL6opZ3IwReX9KJ-TsVGoUbUgC24Pz9aFqEe9ePhcI/edit?usp=sharing";

	JLabel label = new JLabel(mensaje);
	JLabel linkLabel = new JLabel(linkTexto);
	linkLabel.setForeground(Color.BLUE.darker());

	linkLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
	linkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
	    public void mouseClicked(java.awt.event.MouseEvent evt) {
		try {
		    Desktop.getDesktop().browse(new URI(url));
		} catch (IOException | URISyntaxException e) {
		    e.printStackTrace();
		}
	    }
	});

	JPanel panel = new JPanel(new FlowLayout(FlowLayout.LEFT));
	panel.add(label);
	panel.add(linkLabel);

	JOptionPane.showMessageDialog(null, panel, "Enlace Web", JOptionPane.PLAIN_MESSAGE);

    }

}
