package vista;

import javax.swing.JCheckBox;
import javax.swing.JTable;
import modelo.BotonEditor;
import modelo.BotonRenderer;
import modelo.ModeloTabla;

/**
 *
 * @author usuario
 */
public class ReporteGUI extends javax.swing.JDialog {

    private final ModeloTabla modeloTabla;
    private final BotonEditor botonEditor;

    public JTable getTabla() {
        return tabla;
    }

    public ModeloTabla getModeloTabla() {
        return modeloTabla;
    }

    public BotonEditor getBotonEditor() {
        return botonEditor;
    }

    /**
     * Creates new form Reporte
     *
     * @param parent
     * @param modal
     */
    public ReporteGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modeloTabla = new ModeloTabla();
        botonEditor = new BotonEditor(new JCheckBox(), tabla);
        tabla.setModel(modeloTabla);

        // Personalizar el renderizado y la edición de la última columna
        tabla.getColumnModel().getColumn(5).setCellRenderer(new BotonRenderer());
        tabla.getColumnModel().getColumn(5).setCellEditor(botonEditor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTES");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
