package vista;

import javax.swing.JCheckBox;
import modelo.BotonEditor;
import modelo.BotonRenderer;
import modelo.ModeloTabla;

/**
 *
 * @author usuario
 */
public class ReporteGUI extends javax.swing.JDialog {

    private final ModeloTabla modeloTabla;
    private BotonEditor botonEditor;

    public ModeloTabla getModeloTabla() {
	return modeloTabla;
    }

    /**
     * Creates new form Reporte
     *
     * @param parent
     * @param modal
     */
    public ReporteGUI(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
	modeloTabla = new ModeloTabla();
	botonEditor = new BotonEditor(new JCheckBox());
	tabla.setModel(modeloTabla);

	// Personalizar el renderizado y la edición de la última columna
	tabla.getColumnModel().getColumn(5).setCellRenderer(new BotonRenderer());
	tabla.getColumnModel().getColumn(5).setCellEditor(botonEditor);

	// Agregar algunos datos de ejemplo
	modeloTabla.addRow(new Object[]{"Dato 1", "Dato 2", "Dato 3", "Dato 4", "Dato 5", "Botón 1"});
	modeloTabla.addRow(new Object[]{"Dato 6", "Dato 7", "Dato 8", "Dato 9", "Dato 10", "Botón 2"});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTES");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
